name = "def"
main = "src/index.js"
compatibility_date = "2025-10-18"

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "def_dict"
database_name = "def-dict"
database_id = "b00dc587-1c70-48ff-9976-3c9895d86830"
