name = "def"
main = "src/index.js"
compatibility_date = "2026-07-28"
compatibility_flags = [ "nodejs_compat"]

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "def_dict"
database_name = "def-dict"
database_id = "b00dc587-1c70-48ff-9976-3c9895d86830"

[[rules]]
type = "Text"
globs = ["./src/lib/shell.tpl.html"]
fallthrough = true

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
