name = "def"
main = "src/index.js"
compatibility_date = "2026-07-28"
compatibility_flags = [ "nodejs_compat"]

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "def_dict"
database_name = "def-dict"
database_id = "b00dc587-1c70-48ff-9976-3c9895d86830"

[[ratelimits]]
name = "ABNORMAL_LIMITER"
namespace_id = "1001"
  [ratelimits.simple]
  limit = 20
  period = 60

[[rules]]
type = "Text"
globs = ["./src/lib/shell.tpl.html"]
fallthrough = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true

